services:
  s5:
    image: postgres:15
    container_name: s5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: dbmsS5
    ports:
      - "5433:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: dbms_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:yourpassword@s5:5432/dbmsS5
    depends_on:
      s5:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:
